[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
sepolia = "https://1rpc.io/sepolia"

[etherscan]
sepolia = { key = "https://sepolia.etherscan.io" }